가spring:
  config:
    activate:
      on-profile: prod
  jpa:
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        show_sql: false
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
