name: leets-actions
run-name: Running
on:
  push:
    branches:
      - main
      - 'releases/**'

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: gitactionbucket
  AWS_CODE_DEPLOY_APPLICATION: cicd-test-cd
  AWS_CODE_DEPLOY_GROUP: cicd-test-cd-group
  APPLICATION: ${{ secrets.APPLICATION }}
  WORKING_DIRECTORY: ./

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: 환경변수 설정
        run: |
          echo "${{env.APPLICATION}}" > ./src/main/resources/application.yml

      - name: gradlew에 실행 권한 부여
        run: chmod +x gradlew
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: 프로젝트 빌드
        run: ./gradlew clean build -x test

      - name: DockerHub 로그인
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 도커 이미지 빌드 및 푸시
        run: |
          docker build -t ayeonii/leets-be:latest .
          docker push ayeonii/leets-be:latest

      - name: 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_IDENTITYFILE }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd server
            docker compose -f docker-compose.yml down leets-be
            docker compose -f docker-compose.yml pull leets-be
            docker compose -f docker-compose.yml up -d leets-be
